### ISSUE TITLE
How to use `create_arbitrary_line`

### ISSUE THREAD

**Issue by dsourajit** [JintaoLee-Roger/cigvis#21]
Trying the example at [Display an arbitray line &#8212; CIGVis](https://cigvis.readthedocs.io/en/latest/gallery/3Dvispy/14_arbitrary_line.html) with my own volume data in `m_cube` gives me this error.

```Python
>>> type(m_cube)
<class 'numpy.ndarray'>
>>> m_cube.shape
(251, 501, 241)
>>> nodes=cigvis.create_slices(m_cube)
>>> nodes+=cigvis.create_arbitrary_line(anchor=[[0, 0], [90, 190], [190, 50]],volume=m_cube,nodes=nodes)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/pynew/lib/python3.12/site-packages/cigvis/vispyplot.py", line 1135, in create_arbitrary_line
    return [ArbLineNode(path, anchor, data, volume, cmap, clim, hstep, vstep, **kwargs)] # yapf: disable
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pynew/lib/python3.12/site-packages/cigvis/vispynodes/meshnode.py", line 274, in __init__
    self.preprocess(path, anchor, data, volume)
  File "/home/anaconda3/envs/pynew/lib/python3.12/site-packages/cigvis/vispynodes/meshnode.py", line 326, in preprocess
    pout, pdata = surfaceutils.extract_data(self.volume, self.path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/pynew/lib/python3.12/site-packages/cigvis/utils/surfaceutils.py", line 292, in extract_data
    N = p.shape[0]
        ^^^^^^^
AttributeError: 'tuple' object has no attribute 'shape'
```

Is this a bug or am I using something incorrectly?

**Comment by JintaoLee-Roger** [comment]
Related to #20  and fixed by [v0.1.4](https://github.com/JintaoLee-Roger/cigvis/tree/v0.1.4)
